
export enum ActionTypes {
    FETCH_CHARACTERS = "APP/FETCH_CHARACTERS",
    SET_APP_ERROR = "APP/SET_APP_ERROR",
    SET_TOTAL_PAGE = "APP/SET_TOTAL_PAGE",
    SET_NEXT_PAGE = "APP/SET_NEXT_PAGE",
    REMOVE_CHARACTERS = "APP/REMOVE_CHARACTERS",
    TOGGLE_IS_FETCHING = "APP/TOGGLE_IS_FETCHING"
}